### ISSUE TITLE
Processing example crashes on startup

### ISSUE THREAD

**Issue by b2renger** [pif/android-select-file#1]
Hello,

I'm trying to use the processing android lib, with processing 2.2.1, targetting a nexus 5 on 5.1.1

The example provided crashes with this error :-1: 

FATAL EXCEPTION: main
Process: processing.test.select, PID: 26412
java.lang.NullPointerException: Attempt to get length of null array
    at java.util.TimSort.sort(TimSort.java:169)
    at java.util.Arrays.sort(Arrays.java:2010)
    at select.files.SelectDialog.sortData(Unknown Source)
    at select.files.SelectDialog.getData(Unknown Source)
    at select.files.SelectDialog.updateCurrentList(Unknown Source)
    at select.files.SelectDialog.onCreate(Unknown Source)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
    at android.app.Dialog.show(Dialog.java:274)
    at select.files.SelectLibrary$1.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

I remember having already used this great lib sometime ago, but I don't remember on which processing version nor android version I used at the time.

Something must have been broken with an update. I'll try to dig in the code a bit, but help would be very welcome.

**Comment by pif** [comment]
Haven't tried support for the mentioned versions of Processing. 

From what I see, `null` can be returned here:
https://github.com/pif/android-select-file/blob/master/src/processing/files/SelectActivity.java#L125-L126

Please, make sure provided path is really a directory and it exists. 

Method `listFiles(...)` (according to [javadocs](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles%28java.io.FileFilter%29)) can return `null`:

`Returns null if this abstract pathname does not denote a directory, or if an I/O error occurs.`

**Comment by b2renger** [comment]
Thanks for your help.

In fact it's my fault, you just need to be sure to add permission 'WRITE_EXTERNAL_STORAGE' and it works perfectly.
